### ISSUE TITLE
Wrong mapping actuator again block version 

### ISSUE THREAD

**Issue by elonkusk** [uniworld-io/unichain-core#24]
**Describe the bug**
Wrong mapping actuator again block version 
**To Reproduce**
1. Running testnet at master commit 1a601399b6978bcab3cd414529f11349b4f942f8
2. Upgrade to block ver 2
3. Make tx withdraw token urc30
4. Got actuator activated is TokenWithdrawFutureActuatorV3
5. Try to represent the bug on block v2 but withdraw success, it should be an error as described at [https://github.com/uniworld-io/unichain-core/issues/11]

**Expected behavior**

-  the actuator activated should be TokenWithdrawFutureActuator
- withdraw will get error

**Log**
`17:24:10.593 INFO  [pool-42-thread-1] [DB](SnapshotManager.java:283) flush cost:2, create checkpoint cost:1, refresh cost:1
17:24:10.614 INFO  [pool-42-thread-1] [actuator](TokenWithdrawFutureActuatorV3.java:48) TokenWithdrawFutureActuatorV3 owner_address: "D\361\271K6\332\352*\320\312Yj\366\211\320\375)\274\317\330E"
token_name: "ssi"`

**Comment by realelonmusk102** [comment]
Watch at: [](https://github.com/uniworld-io/unichain-core/pull/25)

- Now can represent withdraw bug on v2 testnet :
`wallet> GetAccount US1xxmn45vcHMWyRoT969NBtLsPuLmVkMc`
`"future_supply": {
		"total_deal": 1,
		"lower_time": 1640044800000,
		"upper_time": 1640044800000,
		"total_balance": 60000000,
		"lower_tick": "442c3eefbfbd1c58efbfbd2aefbfbd623d09efbfbd7a513d7adf84efbfbd2c5f31363430303434383030303030",
		"upper_tick": "442c3eefbfbd1c58efbfbd2aefbfbd623d09efbfbd7a513d7adf84efbfbd2c5f31363430303434383030303030"
	},
`

`13:19:17.764 ERROR [pool-48-thread-1] [actuator](WithdrawFutureActuator.java:46) null
java.lang.NullPointerException: null
        at org.unichain.core.actuator.WithdrawFutureActuator.withdraw(WithdrawFutureActuator.java:121)
        at org.unichain.core.actuator.WithdrawFutureActuator.execute(WithdrawFutureActuator.java:41)
        at org.unichain.common.runtime.RuntimeImpl.setupPrecompiled(RuntimeImpl.java:161)
        at org.unichain.common.runtime.RuntimeImpl.setup(RuntimeImpl.java:169)
        at org.unichain.core.db.TransactionTrace.exec(TransactionTrace.java:136)
        at org.unichain.core.db.Manager.processTransaction(Manager.java:1293)
        at org.unichain.core.db.Manager.pushTransaction(Manager.java:751)
        at org.unichain.core.Wallet.broadcastTransaction(Wallet.java:411)
        at org.unichain.core.services.RpcApiService$WalletApi.broadcastTransaction(RpcApiService.java:905)
        at org.unichain.api.WalletGrpc$MethodHandlers.invoke(WalletGrpc.java:8646)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:707)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
`
`13:19:15.104 INFO  [UnichainJClientWorker-3] [net](AdvService.java:152) Ready to broadcast block BlockCapsule
[ blockVersion=2
hash=000000000000c2b398286a62275f3c3b1cdfe1add7e522996ef196b14966da06
number=49843
parentId=000000000000c2b24ef1b2e9530801340c91bf0c6a64ecaf0c47bb3a2caeffa5
witness address=44f1b94b36daea2ad0ca596af689d0fd29bccfd845
generated by myself=false
generate time=2021-12-22 13:19:15.0
txs are empty
]
`

**Comment by realelonmusk102** [comment]
got v2 withdraw token error on testnet:

- account:
- token future deals: 
`"token_future": [
		{
			"key": "SSI",
			"value": {
				"token_name": "SSI",
				"total_deal": 1,
				"lower_bound_time": 1640044800000,
				"upper_bound_time": 1640044800000,
				"total_value": 3000000,
				"lower_tick": "442c3eefbfbd1c58efbfbd2aefbfbd623d09efbfbd7a513d7adf84efbfbd2c5f5353495f31363430303434383030303030",
				"upper_tick": "442c3eefbfbd1c58efbfbd2aefbfbd623d09efbfbd7a513d7adf84efbfbd2c5f5353495f31363430303434383030303030"
			}
		}
	]
`
- withdraw error:
`13:36:38.587 ERROR [pool-48-thread-1] [actuator](TokenWithdrawFutureActuator.java:62) null
java.lang.NullPointerException: null
        at org.unichain.core.actuator.TokenWithdrawFutureActuator.withdraw(TokenWithdrawFutureActuator.java:136)
        at org.unichain.core.actuator.TokenWithdrawFutureActuator.execute(TokenWithdrawFutureActuator.java:53)
        at org.unichain.common.runtime.RuntimeImpl.setupPrecompiled(RuntimeImpl.java:161)
        at org.unichain.common.runtime.RuntimeImpl.setup(RuntimeImpl.java:169)
        at org.unichain.core.db.TransactionTrace.exec(TransactionTrace.java:136)
        at org.unichain.core.db.Manager.processTransaction(Manager.java:1293)
        at org.unichain.core.db.Manager.pushTransaction(Manager.java:751)
        at org.unichain.core.Wallet.broadcastTransaction(Wallet.java:411)
        at org.unichain.core.services.RpcApiService$WalletApi.broadcastTransaction(RpcApiService.java:905)
        at org.unichain.api.WalletGrpc$MethodHandlers.invoke(WalletGrpc.java:8646)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:707)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
`

**Comment by realelonmusk102** [comment]
@elonkusk fixed withdraw issue #11

- upgrade to block ver 3 
- withdraw future fund of US1xxmn45vcHMWyRoT969NBtLsPuLmVkMc :
`"future_supply": {
		"total_deal": 1,
		"lower_time": 1640044800000,
		"upper_time": 1640044800000,
		"total_balance": 60000000,
		"lower_tick": "442c3eefbfbd1c58efbfbd2aefbfbd623d09efbfbd7a513d7adf84efbfbd2c5f31363430303434383030303030",
		"upper_tick": "442c3eefbfbd1c58efbfbd2aefbfbd623d09efbfbd7a513d7adf84efbfbd2c5f31363430303434383030303030"
	},
`
- successfully withdrew:
`wallet> WithdrawFuture 
{
	"raw_data":{
		"contract":[
			{
				"parameter":{
					"value":{
						"owner_address":"442c3ed61c58aa2af9623d09f37a513d7adf84f82c"
					},
					"type_url":"type.googleapis.com/protocol.FutureWithdrawContract"
				},
				"type":"FutureWithdrawContract"
			}
		],
		"ref_block_bytes":"da8d",
		"ref_block_hash":"5bddc75fa45ca98e",
		"expiration":1640197986000,
		"timestamp":1640197928309
	},
	"raw_data_hex":"0a02da8d22085bddc75fa45ca98e40d0adac9bde2f5a520834124e0a33747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e4675747572655769746864726177436f6e747261637412170a15442c3ed61c58aa2af9623d09f37a513d7adf84f82c70f5eaa89bde2f"
}
txid is: 2703ac36a66ce1c90c4379101a2902aae1c2ea51e8af92f197b0200e99ef8699
WithdrawFuture of US1xxmn45vcHMWyRoT969NBtLsPuLmVkMc successful !!
`

**Comment by realelonmusk102** [comment]
@elonkusk alsoe resolved #11 for token:

- upgrade to block ver 3
- withdraw future token deal of account: US1xxmn45vcHMWyRoT969NBtLsPuLmVkMc
`"token_future": [
		{
			"key": "SSI",
			"value": {
				"token_name": "SSI",
				"total_deal": 1,
				"lower_bound_time": 1640044800000,
				"upper_bound_time": 1640044800000,
				"total_value": 3000000,
				"lower_tick": "442c3eefbfbd1c58efbfbd2aefbfbd623d09efbfbd7a513d7adf84efbfbd2c5f5353495f31363430303434383030303030",
				"upper_tick": "442c3eefbfbd1c58efbfbd2aefbfbd623d09efbfbd7a513d7adf84efbfbd2c5f5353495f31363430303434383030303030"
			}
		}` 
- successfully withdrew: 
`txid is: 655e35ac3aedc7484ea8679bc75146a87fa46a50218d69b5e854ff7b40976893
withdrawTokenFuture of US1xxmn45vcHMWyRoT969NBtLsPuLmVkMc token ssi successful !!`
