### ISSUE TITLE
force checking zero division by token exchange factors in TokenExchangeActuator

### ISSUE THREAD

**Issue by elonkusk** [uniworld-io/unichain-core#29]
**Is your feature request related to a problem? Please describe.**
- token exchange code applied but actually running on block v2
- token exchange contract model applied, new urc30 created with factor equals ZERO
- upgrade to block v3
- some one try to exchange  unw --> urc30 token with basic div: token_exchanged = unw_amount * token_factor/unw_factor, it might cause:
  - zero div error
  - overflow number

**Describe the solution you'd like**

- validate exchange factors before exchange

**Comment by realelonmusk102** [comment]
@elonkusk 

- fixed on branch https://github.com/uniworld-io/unichain-core/tree/forceCheckExchangeTokenFactors
- represent error & validation:
`java.lang.IllegalArgumentException: Exchange unw factor must be positive
	at org.springframework.util.Assert.isTrue(Assert.java:68)
	at org.unichain.core.actuator.TokenExchangeActuator.validate(TokenExchangeActuator.java:122)
	at org.unichain.core.Wallet.createTransactionCapsule(Wallet.java:330)
	at org.unichain.core.services.RpcApiService.createTransactionCapsule(RpcApiService.java:173)
	at org.unichain.core.services.RpcApiService.access$700(RpcApiService.java:59)
	at org.unichain.core.services.RpcApiService$WalletApi.exchangeToken(RpcApiService.java:1204)
	at org.unichain.api.WalletGrpc$MethodHandlers.invoke(WalletGrpc.java:8694)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:707)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by elonkusk** [comment]
@realelonmusk102  what happen when token created with exchange factors on block v2 ?

- new token model with exchange factors included:
`message CreateTokenContract {
  bytes owner_address = 1;
  string name = 2;
  string abbr = 3;
  int64 max_supply = 4;
  int64 total_supply = 5;
  int64 start_time = 6;
  int64 end_time = 7;
  string description = 8;
  string url = 9;
  int64 fee = 10;
  int64 extra_fee_rate = 11;
  int64 fee_pool = 12;
  int64 burned = 13;
  int64 latest_operation_time = 14;
  int64 lot =15;
  int64 fee_pool_origin = 16;
  **int64 exch_unx_num = 17; //#unw
  int64 exch_num = 18; //exchange to #token**
  int64 critical_update_time = 19;//critical update time, ex: fee, ownership...
}`
- exch_unx_num/exch_num will be included but not validated, not used on block v2
- when upgrade to block v3, these factors will be used, lead to abnormal behavio, ex: invalid values.
- we should preset exch_num/exch_unx_num to zero to mark as invalid
